# This is a basic workflow to help you get started with Actions

name: Update the webpage list

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Run update script
        run: |
          sudo apt install python3 python3-pip tor -y
          pip3 install requests bs4 tqdm stem fake_useragent PySocks
          killall tor
          cat > torrc <<EOF
          SocksPort 9052
          ControlPort 5090
          CookieAuthentication 0
          EOF
          sudo tor -f torrc & 
          sudo netstat -tulnp | grep tor
          python3 updatelist.py

      - name: Commit to repo
        run: |
          sudo apt install git -y
          git config user.email "204460195+Scratch2033Alt@users.noreply.github.com"
          git config user.name "Scratch2033Alt"
          rm -rf pages/*
          git config --global http.postBuffer 524288000
          git config --global http.lowSpeedLimit 0
          git config --global http.lowSpeedTime 999999
          git gc
          git add .
          git commit -m "Updated domains and pages."
          git remote add origin https://Scratch2033Alt:{GITHUB_TOKEN}@github.com/Scratch2033Alt/SearchPlus.git
          git push --no-verify origin main
